import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google"
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({subsets:['latin']})
export default function RootLayout({
  children,
  searchModal,
}: Readonly<{
  children: React.ReactNode;
  searchModal: React.ReactNode;

}>) {
  
  return (
    <html lang="en">
      
      <body
        className={`${inter.className}`}
      >
        <Providers>
        
        {children}
       
        <Toaster/>
        </Providers>
        {searchModal}
      </body>
    </html>
  );
}
