import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/toaster";
import {Analytics}  from "@vercel/analytics/next";
export const metadata: Metadata = {
  title: "For Movies",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
  searchModal,
}: Readonly<{
  children: React.ReactNode;
  searchModal: React.ReactNode;

}>) {
  
  return (
    <html lang="en" className="dark">
      
      <body className="bg-formovies-dark text-white font-body antialiased">
        <Providers>
        
        {children}
       
        <Toaster/>
        </Providers>
        {searchModal}
        <Analytics />
      </body>
    </html>
  );
}
